models/LoginForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;
use app\modules\admin\models\User;

/**
 * LoginForm is the model behind the login form.
 *
 * @property User|null $user This property is read-only.
 *
 */
class LoginForm extends Model {

    public $email;
    public $password;
    public $rememberMe = true;
    private $_user = false;

    /**
     * @return array the validation rules.
     */
    public function rules() {
        return [
                [['email', 'password'], 'required'],
                ['rememberMe', 'boolean'],
                ['password', 'validatePassword'],
        ];
    }

    public function attributeLabels() {
        return [
            'rememberMe' => 'Запомнить меня',
            'email' => 'Email',
            'password' => 'Пароль',
        ];
    }

    /**
     * Validates the password.
     * This method serves as the inline validation for password.
     *
     * @param string $attribute the attribute currently being validated
     * @param array $params the additional name-value pairs given in the rule
     */
    public function validatePassword($attribute, $params) {
        if (!$this->hasErrors()) {
            $user = $this->getUser();

            if (!$user || !$user->validatePassword($this->password)) {
                $this->addError($attribute, 'Неверный Email или пароль.');
            }
        }
    }

    /**
     * Logs in a user using the provided username and password.
     * @return bool whether the user is logged in successfully
     */
    public function login() {
        if ($this->validate()) {
            return Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600 * 24 * 30 : 0);
        }
        return false;
    }

    /**
     * Finds user by [[username]]
     *
     * @return User|null
     */
    public function getUser() {
        if ($this->_user === false) {
            $this->_user = User::findByEmail($this->email);
        }

        return $this->_user;
    }

}

models/SignupForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;
use app\modules\admin\models\User;

/**
 * Signup form
 */
class SignupForm extends Model {

    public $email;
    public $username;
    public $phone;
    public $password;

    /**
     * {@inheritdoc}
     */
    public function rules() {
        return [
                [['email', 'username', 'password'], 'required'],
                [['email', 'username', 'password'], 'string', 'max' => 50],
                ['username', 'string', 'min' => 2],
                ['password', 'string', 'min' => 5],
                [['email', 'username', 'password'], 'trim'],
                ['email', 'email'],
                ['email', 'unique', 'targetClass' => 'app\modules\admin\models\User', 'message' => 'Этот Email уже занят.'],
        ];
    }

    public function attributeLabels() {
        return [
            'email' => 'Email',
            'username' => 'ФИО',
            'password' => 'Пароль',
        ];
    }

    /**
     * Signs user up.
     *
     * @return User|null the saved model or null if saving fails
     */
    public function signup() {
        if (!$this->validate()) {
            return null;
        }

        $user = new User();
        $user->email = $this->email;
        $user->username = $this->username;
        $user->password = $this->password;
        $user->registration_date = date("Y-m-d");
        $user->role = 'semantic';		

        return $user->save() ? $user : null;
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\modules\admin\models\Project;
use app\modules\admin\models\Task;
use app\modules\admin\models\TaskSearch;
use app\models\SignupForm;

class SiteController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                        [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                        [
                        'allow' => true,
                        'actions' => ['login', 'signup'],
                        'roles' => ['?'],
                    ],
                        [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
		
		$searchModel = new TaskSearch();
		$searchModel->statusParam = '1';
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		
		$dataProvider->setSort([
            'defaultOrder' => [
				'deadline' => SORT_ASC
			]
        ]);
		
		$dataProvider->sort->attributes['fire'] = [
            'asc' => ['fire' => SORT_DESC],
            'desc' => ['fire' => SORT_ASC],
        ];
				
		return $this->render('status1', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);		
		
    }
		
	public function actionStatus2() {
		
        $searchModel = new TaskSearch();
		$searchModel->statusParam = '2';
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		
		$dataProvider->setSort([
            'defaultOrder' => [
				'deadline' => SORT_ASC
			]
        ]);
		
		$dataProvider->sort->attributes['fire'] = [
            'asc' => ['fire' => SORT_DESC],
            'desc' => ['fire' => SORT_ASC],
        ];
				
		return $this->render('status2', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
		
    }
	
	public function actionUpdate($id) {
		
		$model = Task::findOne($id);

        if ($model->load(Yii::$app->request->post())) {
			
			$model->status = '2';
			
			if ($model->save()) {
				return $this->redirect(['index']);
			}
        }

        return $this->render('update', [
                    'model' => $model,
        ]);

    }	
	
	public function actionView($id) {
		
        return $this->render('view', [
                    'model' => Task::findOne($id),
        ]);

    }	
		
    public function actionSignup() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        $this->layout = '//main-signup';

        return $this->render('signup', [
                    'model' => $model,
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';

        $this->layout = '//main-login';
        return $this->render('login', [
                    'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

}

views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

?>
<div class="content-wrapper">
    <section class="content-header">
        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>

<footer class="main-footer">   
    Разработка <a href="#">TEO</a>.
</footer>

views/layouts/header.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */
?>

<header class="main-header">

    <?= Html::a('<span class="logo-mini">ТЗ</span><span class="logo-lg">' . Yii::$app->name . '</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">	
		<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        </a>

        <div class="navbar-custom-menu">

            <ul class="nav navbar-nav">
			
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">                        
                       <span class="hidden-xs"><?= Yii::$app->user->identity->username ?></span>					
                    </a>                   
                </li>   
				<li class="dropdown user user-menu">
				<?= Html::a(
                                    'Выход <i class="fa fa-sign-out"></i>',
                                    ['/site/logout'],
                                    ['data-method' => 'post', 'class' => 'hidden-xs']
                                ) ?>				
                   
                </li> 		                      
				
            </ul>
        </div>
    </nav>
</header>

views/layouts/left.php
<aside class="main-sidebar">

    <section class="sidebar">     

        <?= dmstr\widgets\Menu::widget( 
            [
                'options' => ['class' => 'sidebar-menu tree', 'data-widget'=> 'tree'],
                'items' => [
                    ['label' => 'Главное меню', 'options' => ['class' => 'header']],					
					['label' => 'Исходные ключевики', 'icon' => 'calendar-o', 'url' => ['site/index']],
					['label' => 'Готовое ТЗ', 'icon' => 'calendar-check-o', 'url' => ['site/status2']],                    
                ],
            ]
        ) ?>

    </section>

</aside>

views/layouts/main-login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main-signup.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

    if (class_exists('backend\assets\AppAsset')) {
        backend\assets\AppAsset::register($this);
    } else {
        app\assets\AppAsset::register($this);
    }

    dmstr\web\AdminLteAsset::register($this);

    $directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="shortcut icon" href="web/favicon.ico" type="image/x-icon" />
        <?= Html::csrfMetaTags() ?>		
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
    <?php $this->beginBody() ?>
    <div class="wrapper">

        <?= $this->render(
            'header.php',
            ['directoryAsset' => $directoryAsset]
        ) ?>

        <?= $this->render(
            'left.php',
            ['directoryAsset' => $directoryAsset]
        )
        ?>

        <?= $this->render(
            'content.php',
            ['content' => $content, 'directoryAsset' => $directoryAsset]
        ) ?>

    </div>

    <?php $this->endBody() ?>
    </body>
    </html>
    <?php $this->endPage() ?>


	
	
	
	
	
	
	
	
	
	
	
	

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<section class="content">

    <div class="error-page">
        <h2 class="headline text-info"><i class="fa fa-warning text-yellow"></i></h2>

        <div class="error-content">
            <h3><?= $name ?></h3>

            <p>
                <?= nl2br(Html::encode($message)) ?>
            </p>

            <p>
                The above error occurred while the Web server was processing your request.
                Please contact us if you think this is a server error. Thank you.
                Meanwhile, you may <a href='<?= Yii::$app->homeUrl ?>'>return to dashboard</a> or try using the search
                form.
            </p>

            <form class='search-form'>
                <div class='input-group'>
                    <input type="text" name="search" class='form-control' placeholder="Search"/>

                    <div class="input-group-btn">
                        <button type="submit" name="submit" class="btn btn-primary"><i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</section>

views/site/login.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Система подготовки ТЗ для авторов';

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
?>

<div class="login-box">
    <div class="login-logo">
        Система подготовки ТЗ для авторов
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Войдите, чтобы начать сеанс</p>

        <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>

        <?=
                $form
                ->field($model, 'email', $fieldOptions1)
                ->label(false)
                ->textInput(['placeholder' => $model->getAttributeLabel('email')])
        ?>

        <?=
                $form
                ->field($model, 'password', $fieldOptions2)
                ->label(false)
                ->passwordInput(['placeholder' => $model->getAttributeLabel('password')])
        ?>

        <div class="row">
            <div class="col-xs-8">
<?= $form->field($model, 'rememberMe')->checkbox() ?>
            </div>
            <!-- /.col -->
            <div class="col-xs-4">
        <?= Html::submitButton('Войти', ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
            </div>
            <!-- /.col -->
        </div>


<?php ActiveForm::end(); ?>      
       
<?= Html::a('Регистрация нового пользователя', ['signup']) ?>

    </div>
    <!-- /.login-box-body -->
</div><!-- /.login-box -->

views/site/signup.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-user form-control-feedback'></span>"
];

$fieldOptions3 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-earphone form-control-feedback'></span>"
];

$fieldOptions4 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
?>
<div class="login-box">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="login-box-body">

        <p>Заполните следующие поля для регистрации:</p>

        <?php $form = ActiveForm::begin(['id' => 'form-signup', 'enableClientValidation' => false]); ?>

        <?= $form->field($model, 'email', $fieldOptions1)->label(false)->textInput(['placeholder' => $model->getAttributeLabel('email')]) ?>

        <?= $form->field($model, 'username', $fieldOptions2)->label(false)->textInput(['placeholder' => $model->getAttributeLabel('username')]) ?>

        <?= $form->field($model, 'password', $fieldOptions4)->label(false)->passwordInput(['placeholder' => $model->getAttributeLabel('password')]) ?>

        <div class="form-group">
            <?= Html::submitButton('Зарегистрироваться', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

views/site/status1.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\Pjax;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;

$this->title = 'ТЗ (исходный список ключевиков)';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="task-index">

    <div class="panel panel-default panel-body">
	
	<?php $projects = (new \yii\db\Query())
					->select(['project_id AS id', 'project.name AS name'])
					->distinct()
					->from('task')
					->join('LEFT JOIN', 'project', 'project_id = project.id')
					->where(['status' => '1'])
					->orderBy('project.name')
					->all(); ?>
	
		<?php Pjax::begin(['id' => 'pjax_grid']); ?>

        <?=
        GridView::widget([
            'id' => 'grid',
            'dataProvider' => $dataProvider,
			'filterModel' => $searchModel,
            'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
				[
                    'attribute' => 'fire',	
                    'label' => Html::img('@web/images/fire.png', ['height' => '19px', 'width' => 'auto']),	
					'encodeLabel' => false,
                    'content' => function($data) {
                        if ($data->fire == 1)							
							return Html::img('@web/images/fire.png', ['height' => '20px', 'width' => 'auto']);
                    },
					'contentOptions' => ['style' => 'text-align:center;'],
					'headerOptions' => ['style' => 'text-align:center;'],					
                ],
				[
                    'attribute' => 'name',
                    'value' => function ($model) {
                        return Html::a(Html::encode($model->name), Url::to(["update?id={$model->id}"]));
                    },
                    'format' => 'raw',
                ],
                [
                    'attribute' => 'status',
                    'content' => function($data) {
                        return $data->statusName;
                    },
                ],
                [
                    'attribute' => 'project_id',
                    'content' => function($data) {
                        return $data->projectName;
                    },
					'filter' => Select2::widget([
                        'model' => $searchModel,
                        'attribute' => 'project_id',
                        'data' => ArrayHelper::Map($projects, 'id', 'name'),
                        'theme' => Select2::THEME_BOOTSTRAP,
                        'pluginOptions' => [
                            'allowClear' => true,
                        ],
                        'options' => [
                            'placeholder' => ''
                        ]
                    ]),
                ],
				'project_TZBinet',
                    [
                    'attribute' => 'date_add',
                    'content' => function($data) {
                        return date('d.m.Y H:i', strtotime($data->date_add));
                    }
                ],
                    [
                    'attribute' => 'deadline',
                    'content' => function($data) {
                        return date('d.m.Y', strtotime($data->deadline));
                    },
					'contentOptions' => function($data) {	
						if ($data->deadline < date('Y-m-d'))
                            return ['style' => 'color:red;'];
                        else
                            return [];						
                    },
                ],
					[
                    'content' => function($data) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ["update?id={$data->id}"], ['title' => 'Редактировать',]);
                    }
                ],
            ],
        ]);
        ?>
		
		<?php Pjax::end(); ?>

    </div>

</div>

views/site/status2.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\Pjax;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;

$this->title = 'Готовое ТЗ';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="task-index">

    <div class="panel panel-default panel-body">
	
	<?php $projects = (new \yii\db\Query())
					->select(['project_id AS id', 'project.name AS name'])
					->distinct()
					->from('task')
					->join('LEFT JOIN', 'project', 'project_id = project.id')
					->where(['status' => '2'])
					->orderBy('project.name')
					->all(); ?>
	
		<?php Pjax::begin(['id' => 'pjax_grid']); ?>

        <?=
        GridView::widget([
            'id' => 'grid',
            'dataProvider' => $dataProvider,
			'filterModel' => $searchModel,
            'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
				[
                    'attribute' => 'fire',	
                    'label' => Html::img('@web/images/fire.png', ['height' => '19px', 'width' => 'auto']),	
					'encodeLabel' => false,
                    'content' => function($data) {
                        if ($data->fire == 1)							
							return Html::img('@web/images/fire.png', ['height' => '20px', 'width' => 'auto']);
                    },
					'contentOptions' => ['style' => 'text-align:center;'],
					'headerOptions' => ['style' => 'text-align:center;'],					
                ],
                [
                    'attribute' => 'name',
                    'value' => function ($model) {
                        return Html::a(Html::encode($model->name), Url::to(["view?id={$model->id}"]));
                    },
                    'format' => 'raw',
                ],
				[
                    'attribute' => 'status',
                    'content' => function($data) {
                        return $data->statusName;
                    },
                ],
                [
                    'attribute' => 'project_id',
                    'content' => function($data) {
                        return $data->projectName;
                    },
					'filter' => Select2::widget([
                        'model' => $searchModel,
                        'attribute' => 'project_id',
                        'data' => ArrayHelper::Map($projects, 'id', 'name'),
                        'theme' => Select2::THEME_BOOTSTRAP,
                        'pluginOptions' => [
                            'allowClear' => true,
                        ],
                        'options' => [
                            'placeholder' => ''
                        ]
                    ]),
                ],
				'project_TZBinet',
                    [
                    'attribute' => 'date_add',
                    'content' => function($data) {
                        return date('d.m.Y H:i', strtotime($data->date_add));
                    }
                ],
                    [
                    'attribute' => 'deadline',
                    'content' => function($data) {
                        return date('d.m.Y', strtotime($data->deadline));
                    },
					'contentOptions' => function($data) {	
						if ($data->deadline < date('Y-m-d'))
                            return ['style' => 'color:red;'];
                        else
                            return [];						
                    },
                ],
					[
                    'content' => function($data) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ["view?id={$data->id}"], ['title' => 'Просмотр',]);
                    }
                ],
            ],
        ]);
        ?>
		
		<?php Pjax::end(); ?>

    </div>

</div>

views/site/update.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use rmrevin\yii\module\Comments;

$this->title = $model->name;
?>

<div class="task-form">

	<h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin(); ?>

    <div class="panel panel-default panel-body">  
	
        <div class="row">
		
            <div class="col-md-4"> 
				<?= Html::activeLabel($model, 'project_id') . ': ' . $model->projectName ?> <br>
	
				<?= Html::activeLabel($model, 'project_TZBinet') . ': ' . $model->project_TZBinet ?>                
            </div>
			
            <div class="col-md-4"> 
				<?= Html::activeLabel($model, 'date_add') . ': ' . $model->dateAddFormat ?> <br>
	
				<?= Html::activeLabel($model, 'deadline') . ': ' . $model->deadlineFormat ?>
            </div>
			
            <div class="col-md-4"> 
				<?= Html::activeLabel($model, 'status') . ': ' . $model->statusName ?>
            </div>
			
        </div>
		
        <br>					
			<?= Html::textArea('', $model->keywords, ['id' => 'keywords', 'rows' => 15, 'style'=>'width:100%', 'readonly' => 'readonly']) ?>
			
			<div class="form-group">		
				<span class="btn btn-default" onClick="setSelection()">Выделить все</span>
			</div>
			
            <?= $form->field($model, 'task_text')->textArea(['maxlength' => true, 'rows' => 20]) ?>
    </div>

    <div class="form-group">
        <?= Html::submitButton('Сдать на проверку', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?= Comments\widgets\CommentListWidget::widget([
    'entity' => (string) "task-{$model->id}", // type and id
]);?>

<script type="text/javascript">
	
	function setSelection() {
			
		document.getElementById("keywords").select();
		
		/*var target = document.getElementById('keywords');
		var rng, sel;	
		
		if (document.createRange) {
		  rng = document.createRange();
		  rng.selectNode(target)
		  sel = window.getSelection();
		  sel.removeAllRanges();
		  sel.addRange(rng);
		  //document.execCommand("Copy");
		} else {
		  var rng = document.body.createTextRange();
		  rng.moveToElementText(target);
		  rng.select();
		}*/
	}

</script>

views/site/view.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use rmrevin\yii\module\Comments;

$this->title = $model->name;
?>

<div class="task-form">

	<h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin(); ?>

    <div class="panel panel-default panel-body">  
	
        <div class="row">
		
            <div class="col-md-4"> 
				<?= Html::activeLabel($model, 'project_id') . ': ' . $model->projectName ?> <br>
	
				<?= Html::activeLabel($model, 'project_TZBinet') . ': ' . $model->project_TZBinet ?>                
            </div>
			
            <div class="col-md-4"> 
				<?= Html::activeLabel($model, 'date_add') . ': ' . $model->dateAddFormat ?> <br>
	
				<?= Html::activeLabel($model, 'deadline') . ': ' . $model->deadlineFormat ?>
            </div>
			
            <div class="col-md-4"> 
				<?= Html::activeLabel($model, 'status') . ': ' . $model->statusName ?>
            </div>
			
        </div>
		
        <br>					
			<?= Html::textArea('', $model->keywords, ['id' => 'keywords', 'rows' => 15, 'style'=>'width:100%', 'disabled' => true]) ?>
			
			<div class="form-group">		
			</div>
			
            <?= $form->field($model, 'task_text')->textArea(['maxlength' => true, 'rows' => 20, 'disabled' => true]) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?= Comments\widgets\CommentListWidget::widget([
    'entity' => (string) "task-{$model->id}", // type and id
]);?>

<script type="text/javascript">
	
	function setSelection() {
		
		var target = document.getElementById('keywords');
		var rng, sel;
		if (document.createRange) {
		  rng = document.createRange();
		  rng.selectNode(target)
		  sel = window.getSelection();
		  sel.removeAllRanges();
		  sel.addRange(rng);
		  //document.execCommand("Copy");
		} else {
		  var rng = document.body.createTextRange();
		  rng.moveToElementText(target);
		  rng.select();
		}
	}

</script>