modules/admin/controllers/GroupController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\modules\admin\models\Group;
use app\modules\admin\models\GroupSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * GroupController implements the CRUD actions for Group model.
 */
class GroupController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Group models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new GroupSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Group model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Group model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Group();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Group model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Group model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Group model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Group the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Group::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/admin/controllers/ProjectController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\modules\admin\models\Project;
use app\modules\admin\models\ProjectSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ProjectController implements the CRUD actions for Project model.
 */
class ProjectController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Project models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProjectSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Project model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Project model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Project();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Project model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Project model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Project model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Project the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Project::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/admin/controllers/TaskController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\modules\admin\models\Task;
use app\modules\admin\models\TaskSearch;
use app\modules\admin\models\TaskGroupCreation;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use app\modules\admin\models\Group;

/**
 * TaskController implements the CRUD actions for Task model.
 */
class TaskController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Task models.
     * @return mixed
     */
    public function actionIndex() {

        $searchModel = new TaskSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
				
		return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionStatus1() {
		
		$searchModel = new TaskSearch();
		$searchModel->statusParam = '1';
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
						
		return $this->render('status1', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);

    }

    public function actionStatus2() {

        $searchModel = new TaskSearch();
		$searchModel->statusParam = '2';
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
				
		return $this->render('status2', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
		
    }

    public function actionStatus3() {

        $searchModel = new TaskSearch();
		$searchModel->statusParam = '3';
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
				
		return $this->render('status3', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
		
    }

    public function actionUsed() {

        $keylist = Yii::$app->request->post('keylist');

        foreach ($keylist as $key) {
            $task = Task::findOne($key);
            $task->status = '3';
            $task->save();
        }

        return 'Статусы обновлены.';
    }
	
	public function actionFire() {

        $keylist = Yii::$app->request->post('keylist');

        foreach ($keylist as $key) {
            $task = Task::findOne($key);
            $task->fire = 1;
            $task->save();
        }

        return 'Пометка установлена.';
    }
	
	public function actionGroup() {

        $keylist = Yii::$app->request->post('keylist');
		
		$group_id = (new \yii\db\Query())
					->select(['max(group_id)'])
					->from('task')
					->scalar();	

		$next_group_id = $group_id + 1;
       
		foreach ($keylist as $key) {
            $task = Task::findOne($key);
            $task->group_id = $next_group_id;
            $task->save();
        }

        return 'ТЗ объединены в группу.';
    }
		
	public function actionDeleteSelectedTasks() {

        $keylist = Yii::$app->request->post('keylist');

        foreach ($keylist as $key) {
			Task::findOne($key)->delete();
        }

        return 'ТЗ удалены.';
    }

    public function actionExportTask() {

		$keylist = Yii::$app->request->post('keylist');
		
		if (empty($keylist)) return 'Отметьте флажками необходимые ТЗ.'; 
        
		$tasks = (new \yii\db\Query())->select([
                    'main_keywords', 'task_text'])
                ->from('task')
				->where(['id' => $keylist])
				->all();
				
		$taskText = '';		
		foreach ($tasks as $task) {		
            //$taskText = $taskText . ($taskText == '' ? '' : '<br>---<br>') . $task['name'] . '<br>' . $task['task_text'];
			$taskText = $taskText . ($taskText == '' ? '' : PHP_EOL . PHP_EOL) . $task['main_keywords'] . PHP_EOL . '!' . PHP_EOL . $task['task_text'];
        }
				
        return $taskText;
    }
	
	public function actionSearch() {

        $search_text = Yii::$app->request->get('text');
		
		$tasks = (new \yii\db\Query())->select([
                    'id', 'name'])
                ->from('task')
				->where(['like', 'main_keywords', $search_text])
				->orWhere(['like', 'additional_keywords', $search_text])
				->orWhere(['like', 'task_text', $search_text])
				->orderBy('id')
				->all();
		
		return $this->render('search', [
                    'tasks' => $tasks,
        ]);
		
    }

    public function actionTest() {			
					

		
    }

    /**
     * Displays a single Task model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Task model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Task();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    public function actionGroupCreation() {

        $model = new TaskGroupCreation();

        if ($model->load(Yii::$app->request->post()) && $model->createMany()) {
            return $this->redirect(['index']);
        }

        return $this->render('group-creation', [
                    'model' => $model,
        ]);
    }

    /**
     * Updates an existing Task model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Task model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Task model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Task the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Task::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

modules/admin/controllers/UserController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\modules\admin\models\User;
use app\modules\admin\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

modules/admin/views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

?>
<div class="content-wrapper">
    <section class="content-header">
        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>

<footer class="main-footer">   
    Разработка <a href="#">TEO</a>.
</footer>

modules/admin/views/layouts/header.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */
?>

<header class="main-header">

    <?= Html::a('<span class="logo-mini">ТЗ</span><span class="logo-lg">' . Yii::$app->name . '</span>', ['task/index'], ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">
		<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        </a>

        <div class="navbar-custom-menu">

            <ul class="nav navbar-nav">

                <li class="dropdown user user-menu">
				
				<?= Html::a('Перейти на сайт', ['/site/index'], ['class' => 'hidden-xs', 'target' => '_blank']) ?>
                   
                </li>  
				<li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">                        
                        <span class="hidden-xs"><?= Yii::$app->user->identity->username ?> </span>						
                    </a>                   
                </li>  
				<li class="dropdown user user-menu">
					<?= Html::a(
                                    'Выход <i class="fa fa-sign-out"></i>',
                                    ['/site/logout'],
                                    ['data-method' => 'post', 'class' => 'hidden-xs']
                                ) ?>				
                   
                </li> 					
				
            </ul>
        </div>
    </nav>
</header>

modules/admin/views/layouts/left.php
<aside class="main-sidebar">

    <section class="sidebar">  
	
        <?= dmstr\widgets\Menu::widget( 
            [
                'options' => ['class' => 'sidebar-menu tree', 'data-widget'=> 'tree'],
                'items' => [
                    ['label' => 'Админ. панель', 'options' => ['class' => 'header']],
					['label' => 'Проекты', 'icon' => 'book', 'url' => ['project/index']],	
					['label' => 'ТЗ <span class="glyphicon glyphicon-menu-down" style="float:right;padding-right:15px;padding-top:5px;font-size:9px;"></span>', 'encode' => false, 'icon' => 'calendar', 'url' => ['task/index']],
					['label' => 'Исходные ключевики', 'icon' => 'ca lendar-o', 'url' => ['task/status1'],],
					['label' => 'Готовое ТЗ', 'icon' => 'c alendar-check-o', 'url' => ['task/status2'],],
                    ['label' => 'Использованные ТЗ', 'icon' => 'a rchive', 'url' => ['task/status3'],],			
					// fa fa-sort-desc
					/*['label' => 'ТЗ <span class="fa fa-sort-desc" style="float:right;padding-right:15px;"></span>', 'encode' => false, 'icon' => 'calendar', 'url' => ['task/index']],*/
					/*[
                        'label' => 'ТЗ',
                        'icon' => 'calendar',
                        'url' => 'task/index',
						'options' => ['class' => 'active'],
                        'items' => [
                            ['label' => 'Все ТЗ', 'icon' => 'calendar', 'url' => ['task/index'],],
							['label' => 'Исходн. список ключевиков', 'icon' => 'calendar-o', 'url' => ['task/status1'],],
							['label' => 'Готовое ТЗ', 'icon' => 'calendar-check-o', 'url' => ['task/status2'],],
                            ['label' => 'Готовое ТЗ (использовано)', 'icon' => 'archive', 'url' => ['task/status3'],],
                            
                        ],
                    ],*/     				
					//['label' => 'Группы ТЗ', 'icon' => 'folder', 'url' => ['group/index']],
					['label' => 'Пользователи', 'icon' => 'user-o', 'url' => ['user/index']],				
				],					
            ]			
			
        ) ?>

    </section>

</aside>

modules/admin/views/layouts/main-login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

modules/admin/views/layouts/main.php
<?php
//use Yii;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */


if (Yii::$app->controller->action->id === 'login') { 
/**
 * Do not use this code in your template. Remove it. 
 * Instead, use the code  $this->layout = '//main-login'; in your controller.
 */
    echo $this->render(
        'main-login',
        ['content' => $content]
    );
} else {

    if (class_exists('backend\assets\AppAsset')) {
        backend\assets\AppAsset::register($this);
    } else {
        app\assets\AppAsset::register($this);
    }

    dmstr\web\AdminLteAsset::register($this);

    $directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="shortcut icon" href="/web/favicon.ico" type="image/x-icon" />		
        <?= Html::csrfMetaTags() ?>		
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>		
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
    <?php $this->beginBody() ?>
    <div class="wrapper">

        <?= $this->render(
            'header.php',
            ['directoryAsset' => $directoryAsset]
        ) ?>

        <?= $this->render(
            'left.php',
            ['directoryAsset' => $directoryAsset]
        )
        ?>

        <?= $this->render(
            'content.php',
            ['content' => $content, 'directoryAsset' => $directoryAsset]
        ) ?>

    </div>

    <?php $this->endBody() ?>
    </body>
    </html>
    <?php $this->endPage() ?>
<?php } ?>