modules/admin/models/Task.php
<?php

namespace app\modules\admin\models;

use Yii;

/**
 * This is the model class for table "task".
 *
 * @property int $id
 * @property string $name
 * @property string $status
 * @property int $project
 * @property string $project_TZBinet
 * @property string $date_add
 * @property string $deadline
 * @property string $main_keywords
 * @property string $additional_keywords
 * @property string $task_text
 */
class Task extends \yii\db\ActiveRecord {
	
    /**
     * {@inheritdoc}
     */
    public static function tableName() {
        return 'task';
    }

    /**
     * {@inheritdoc}
     */
    public function rules() {
        return [
                [['status', 'project_id', 'project_TZBinet', 'main_keywords'], 'required'],
                [['project_id', 'group_id'], 'integer'],
                [['date_add', 'group_id', 'import_key'], 'safe'],
				['fire', 'default', 'value' => 0],
                [['name', 'status', 'project_TZBinet'], 'string', 'max' => 255],
				[['main_keywords', 'additional_keywords'], 'string', 'max' => 20000],
                [['task_text'], 'string', 'max' => 1500],
				[['deadline'], 'filter', 'filter' => function($value) {
                    if ($value == '')
                        return NULL;
                    return date('Y-m-d', strtotime($value));
                }],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'status' => 'Статус',
            'statusName' => 'Статус',
            'project_id' => 'Проект',
            'projectName' => 'Проект',
            'project_TZBinet' => 'Проект в TZBinet',
            'date_add' => 'Дата создания',
            'deadline' => 'Дедлайн',
            'main_keywords' => 'Основные ключевики',
            'additional_keywords' => 'Дополнительные ключевики',
            'task_text' => 'ТЗ для автора',
			'fire' => 'Горит',
			'keywords' => 'Ключевики',
			'group_id' => 'Группа',
			'groupName' => 'Группа',
			'import_key' => 'Частотность импортируемых ключей',
        ];
    }
	
	public function getKeywords() {		
	
        return (trim($this->main_keywords) . PHP_EOL . '!' . PHP_EOL . trim($this->additional_keywords));
		
    }
	
	public function getDateAddFormat() {		
	
        return date('d.m.Y H:i:s', strtotime($this->date_add));
		
    }
	
	public function getDeadlineFormat() {		
	
        return date('d.m.Y', strtotime($this->deadline));
		
    }

    public function getStatuses() {

        return array(
            '1' => 'Исходные ключевики',
            '2' => 'Готовое ТЗ',
            '3' => 'Использованные ТЗ'
        );
    }
	
	public function getImportKey() {

        return array(
            '1' => 'НЧ',
            '2' => 'СЧ',
            '3' => 'ВЧ'
        );
    }

    public function getStatusName() {

        if ($this->status == 1)
            return 'Исходные ключевики';
        if ($this->status == 2)
            return 'Готовое ТЗ';
        if ($this->status == 3)
            return 'Использованные ТЗ';
    }

    // project 	
    public function getProject() {
        return $this->hasOne(Project::className(), ['id' => 'project_id']);
    }

    public function getProjectName() {
        if (isset($this->project))
            return $this->project->name;
        else
            return '';
    }

	// groupName 	
   /* public function getGroup() {
        return $this->hasOne(Group::className(), ['id' => 'group_id']);
    }

    public function getGroupName() {
        if (isset($this->group))
            return $this->group->name;
        else
            return '';
    }*/
	
    public function beforeSave($insert) {

        if (!parent::beforeSave($insert)) {
            return false;
        }

        if ($insert) {
            $this->date_add = date('Y-m-d H:i:s');
            $this->deadline = date('Y-m-d', strtotime("+3 days"));
        }

        // установим название
        $strings = explode(PHP_EOL, $this->main_keywords);
		
        $name = '';
        if (isset($strings[0]) && !is_numeric(trim($strings[0]))) {
            $name = trim($strings[0]);
        } elseif (isset($strings[1]) && !is_numeric(trim($strings[1]))) {
            $name = trim($strings[1]);
        }

        $this->name = $name;

        return true;
    }

}

modules/admin/controllers/TaskController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\modules\admin\models\Task;
use app\modules\admin\models\TaskSearch;
use app\modules\admin\models\TaskGroupCreation;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use app\modules\admin\models\Group;

/**
 * TaskController implements the CRUD actions for Task model.
 */
class TaskController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Task models.
     * @return mixed
     */
    public function actionIndex() {

        $searchModel = new TaskSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
				
		return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionStatus1() {
		
		$searchModel = new TaskSearch();
		$searchModel->statusParam = '1';
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
						
		return $this->render('status1', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);

    }

    public function actionStatus2() {

        $searchModel = new TaskSearch();
		$searchModel->statusParam = '2';
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
				
		return $this->render('status2', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
		
    }

    public function actionStatus3() {

        $searchModel = new TaskSearch();
		$searchModel->statusParam = '3';
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
				
		return $this->render('status3', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
		
    }

    public function actionUsed() {

        $keylist = Yii::$app->request->post('keylist');

        foreach ($keylist as $key) {
            $task = Task::findOne($key);
            $task->status = '3';
            $task->save();
        }

        return 'Статусы обновлены.';
    }
	
	public function actionFire() {

        $keylist = Yii::$app->request->post('keylist');

        foreach ($keylist as $key) {
            $task = Task::findOne($key);
            $task->fire = 1;
            $task->save();
        }

        return 'Пометка установлена.';
    }
	
	public function actionGroup() {

        $keylist = Yii::$app->request->post('keylist');
		
		$group_id = (new \yii\db\Query())
					->select(['max(group_id)'])
					->from('task')
					->scalar();	

		$next_group_id = $group_id + 1;
       
		foreach ($keylist as $key) {
            $task = Task::findOne($key);
            $task->group_id = $next_group_id;
            $task->save();
        }

        return 'ТЗ объединены в группу.';
    }
		
	public function actionDeleteSelectedTasks() {

        $keylist = Yii::$app->request->post('keylist');

        foreach ($keylist as $key) {
			Task::findOne($key)->delete();
        }

        return 'ТЗ удалены.';
    }

    public function actionExportTask() {

		$keylist = Yii::$app->request->post('keylist');
		
		if (empty($keylist)) return 'Отметьте флажками необходимые ТЗ.'; 
        
		$tasks = (new \yii\db\Query())->select([
                    'main_keywords', 'task_text'])
                ->from('task')
				->where(['id' => $keylist])
				->all();
				
		$taskText = '';		
		foreach ($tasks as $task) {		
            //$taskText = $taskText . ($taskText == '' ? '' : '<br>---<br>') . $task['name'] . '<br>' . $task['task_text'];
			$taskText = $taskText . ($taskText == '' ? '' : PHP_EOL . PHP_EOL) . $task['main_keywords'] . PHP_EOL . '!' . PHP_EOL . $task['task_text'];
        }
				
        return $taskText;
    }
	
	public function actionSearch() {

        $search_text = Yii::$app->request->get('text');
		
		$tasks = (new \yii\db\Query())->select([
                    'id', 'name'])
                ->from('task')
				->where(['like', 'main_keywords', $search_text])
				->orWhere(['like', 'additional_keywords', $search_text])
				->orWhere(['like', 'task_text', $search_text])
				->orderBy('id')
				->all();
		
		return $this->render('search', [
                    'tasks' => $tasks,
        ]);
		
    }

    public function actionTest() {			
					

		
    }

    /**
     * Displays a single Task model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Task model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Task();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    public function actionGroupCreation() {

        $model = new TaskGroupCreation();

        if ($model->load(Yii::$app->request->post()) && $model->createMany()) {
            return $this->redirect(['index']);
        }

        return $this->render('group-creation', [
                    'model' => $model,
        ]);
    }

    /**
     * Updates an existing Task model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Task model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Task model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Task the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Task::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

modules/admin/views/task/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\modules\admin\models\Project;
use app\modules\admin\models\Group;
use kartik\select2\Select2;
use rmrevin\yii\module\Comments;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Task */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="task-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="panel panel-default panel-body">  

        <div class="row">

            <div class="col-md-4"> 

                <?php $projects = Project::find()->orderBy('name')->all(); ?>

                <?=
                $form->field($model, 'project_id')->widget(Select2::classname(), [
                    'data' => ArrayHelper::Map($projects, 'id', 'name'),
                    'options' => ['placeholder' => 'Выберите проект...'],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ]);
                ?>
            </div>
            <div class="col-md-4"> 
                <?= $form->field($model, 'project_TZBinet')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-md-4"> 
                <?= $form->field($model, 'status')->dropDownList($model->statuses); ?>	
            </div>
        </div>

        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#panel1">Ключевики</a></li>
            <li><a data-toggle="tab" href="#panel2">ТЗ для автора</a></li>
        </ul>

        <br>

        <div class="tab-content">
            <div id="panel1" class="tab-pane fade in active">

                <?= $form->field($model, 'main_keywords')->textArea(['maxlength' => true, 'rows' => 10]) ?>

                <?= $form->field($model, 'additional_keywords')->textArea(['maxlength' => true, 'rows' => 10]) ?>

            </div>
            <div id="panel2" class="tab-pane fade">

                <?= $form->field($model, 'task_text')->textArea(['maxlength' => true, 'rows' => 20]) ?>

            </div>
        </div>   	
               
		<?= $form->field($model, 'group_id')->textInput() ?>
				
		<?= $form->field($model, 'import_key')->dropDownList($model->importKey, ['prompt' => 'Выберите значение...']); ?>	

        <div class="row">

            <div class="col-md-2"> 				
                <?=
                $form->field($model, 'date_add')->widget(\yii\jui\DatePicker::classname(), [
                    'language' => 'ru',
                    'dateFormat' => 'dd.MM.yyyy H:i:s',
                    'options' => ['class' => 'form-control', 'disabled' => true],
                ])
                ?>	
            </div>
            <div class="col-md-2"> 
                <?=
                $form->field($model, 'deadline')->widget(\yii\jui\DatePicker::classname(), [
                    'language' => 'ru',
                    'dateFormat' => 'dd.MM.yyyy',
                    'options' => ['class' => 'form-control'],
                ])
                ?>	
            </div>
            <div class="col-md-6"> 
                <?= $form->field($model, 'name')->textInput(['maxlength' => true, 'disabled' => true]) ?>
            </div>
			 <div class="col-md-2"> 
                <?= $form->field($model, 'fire')->dropDownList([0 => 'Нет', 1 => 'Да']); ?>	
            </div>
        </div>

    </div>

    <div class="form-group">
        <?= Html::submitButton('Записать', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?= Comments\widgets\CommentListWidget::widget([
    'entity' => (string) "task-{$model->id}", // type and id
]);?>

modules/admin/views/task/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\TaskSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="task-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'project') ?>

    <?= $form->field($model, 'project_TZBinet') ?>

    <?php // echo $form->field($model, 'date_add') ?>

    <?php // echo $form->field($model, 'deadline') ?>

    <?php // echo $form->field($model, 'main_keywords') ?>

    <?php // echo $form->field($model, 'additional_keywords') ?>

    <?php // echo $form->field($model, 'task_text') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/task/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Task */

$this->title = 'Создание нового ТЗ';
$this->params['breadcrumbs'][] = ['label' => 'Все ТЗ', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="task-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
    ])
    ?>

</div>

modules/admin/views/task/group-creation.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\modules\admin\models\Project;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Task */

$this->title = 'Групповое создание ТЗ';
$this->params['breadcrumbs'][] = ['label' => 'Все ТЗ', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="task-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin(); ?>

    <div class="panel panel-default panel-body">  

        <?php $projects = Project::find()->orderBy('name')->all(); ?>

        <?=
        $form->field($model, 'project_id')->widget(Select2::classname(), [
            'data' => ArrayHelper::Map($projects, 'id', 'name'),
            'options' => ['placeholder' => 'Выберите проект...'],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ]);
        ?>

        <?= $form->field($model, 'project_TZBinet')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'keywords')->textArea(['maxlength' => true, 'rows' => 20]) ?>

    </div>

    <div class="form-group">
        <?= Html::submitButton('Создать', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>  

</div>

modules/admin/views/task/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\Pjax;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use app\modules\admin\models\Group;
use app\modules\admin\models\Project;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\models\TaskSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Все ТЗ';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="task-index">
</p>
<div class="row">
    <div class="col-lg-6">		
        <?= Html::a('Создать', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('<i class="fa fa-clone"></i> Групповое создание ТЗ', ['group-creation'], ['class' => 'btn btn-success']) ?>
        <span class="btn btn-success" onClick="deleteSelectedTasks()"><i class="fa fa-trash-o"></i> Удалить</span>
    </div>	
    <div class="col-lg-6">
        <div class="input-group">
            <?= Html::input('text', '', '', ['id' => 'search_text', 'placeholder' => 'Search', 'size' => 50, 'class' => 'form-control']) ?>
            <span class="input-group-btn">
                <span class="btn btn-default" onClick="searchTask()">Найти</span>
            </span>
        </div>	
    </div>	
</div>		
</p>

<div class="panel panel-default panel-body">

	<?php $projects = (new \yii\db\Query())
					->select(['project_id AS id', 'project.name AS name'])
					->distinct()
					->from('task')
					->join('LEFT JOIN', 'project', 'project_id = project.id')
					->orderBy('project.name')
					->all(); ?>

    <?php Pjax::begin(['id' => 'pjax_grid']); ?>

    <?=
    GridView::widget([
        'id' => 'grid',
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                [
                'class' => 'yii\grid\CheckboxColumn',
                'name' => 'checked',
                'checkboxOptions' => function($model) {
                    return ['value' => $model->id];
                },
				'contentOptions' => ['style' => 'text-align:center;'],
				'headerOptions' => ['style' => 'text-align:center;'],
            ],
            [
                    'attribute' => 'name',
                    'value' => function ($model) {
                        return Html::a(Html::encode($model->name), Url::to(["update?id={$model->id}"]));
                    },
                    'format' => 'raw',
                ],
                [
                'attribute' => 'status',
                'content' => function($data) {
                    return $data->statusName;
                },
            ],
                [
                'attribute' => 'project_id',
                'content' => function($data) {
                    return $data->projectName;
                },
				'filter' => Select2::widget([
                    'model' => $searchModel,
                    'attribute' => 'project_id',
                    'data' => ArrayHelper::Map($projects, 'id', 'name'),
                    'theme' => Select2::THEME_BOOTSTRAP,
                    'pluginOptions' => [
                        'allowClear' => true,
                    ],
                    'options' => [
                        'placeholder' => ''
                    ]
				]),				
			],
			'project_TZBinet',
                [
                'attribute' => 'date_add',
                'content' => function($data) {
                    return date('d.m.Y H:i', strtotime($data->date_add));
                }
            ],
                [
                'attribute' => 'deadline',
                'content' => function($data) {
                    return date('d.m.Y', strtotime($data->deadline));
                },
				'contentOptions' => function($data) {	
					if ($data->deadline < date('Y-m-d'))
                        return ['style' => 'color:red;'];
                    else
                       return [];						
                    },
            ],
                [
                'attribute' => 'group_id',
                'content' => function($data) {
                    return isset($data->group_id) ? $data->group_id : '';
                },   
				'contentOptions' => ['style' => 'width: 50px;'],					
            ],
                ['class' => 'yii\grid\ActionColumn'],
        ],
    ]);
    ?>

    <?php Pjax::end(); ?>

</div>

</div>

<script type="text/javascript">

    function deleteSelectedTasks() {

        var keys = $('#grid').yiiGridView('getSelectedRows');

        if (keys == '') {
            swal({
                title: "",
                text: 'Отметьте флажками необходимые ТЗ',
                confirmButtonColor: "#337ab7"
            });
            return;
        }

        var dialog = confirm('Удалить выбранные ТЗ?');

        if (dialog == true) {

            $.ajax({
                type: "POST",
                url: 'delete-selected-tasks',
                data: {keylist: keys},
                success: function (result) {
                    swal({
                        title: "",
                        text: result,
                        confirmButtonColor: "#337ab7"
                    });
                    $.pjax.reload({container: '#pjax_grid'});
                }
            });
        }
    }

    function searchTask() {

        var search_text = $("#search_text").val().trim();

        if (search_text == '') {
            swal({
                title: "",
                text: 'Укажите текст для поиска.',
                confirmButtonColor: "#337ab7"
            });

            return;
        }

        window.open('search?text=' + search_text);
    }

</script>

modules/admin/views/task/search.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Результаты поиска';
?>

<h1><?= Html::encode('Результаты поиска') ?></h1>

<?php foreach ($tasks as $task): ?>

<p><?= Html::a($task['name'], ["view?id={$task['id']}"]) ?></p>

<?php endforeach; ?>

modules/admin/views/task/status3.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\Pjax;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use app\modules\admin\models\Group;
use app\modules\admin\models\Project;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\models\TaskSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Готовое ТЗ (использовано)';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="task-index">

    <p>
        <?= Html::a('Создать', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('<i class="fa fa-clone"></i> Групповое создание ТЗ', ['group-creation'], ['class' => 'btn btn-success']) ?>
        <span class="btn btn-success" onClick="deleteSelectedTasks()"><i class="fa fa-trash-o"></i> Удалить</span>
    </p>

    <div class="panel panel-default panel-body">
	
		<?php $projects = (new \yii\db\Query())
					->select(['project_id AS id', 'project.name AS name'])
					->distinct()
					->from('task')
					->join('LEFT JOIN', 'project', 'project_id = project.id')
					->where(['status' => '3'])
					->orderBy('project.name')
					->all(); ?>

        <?php Pjax::begin(['id' => 'pjax_grid']); ?>

        <?=
        GridView::widget([
            'id' => 'grid',
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    [
                    'class' => 'yii\grid\CheckboxColumn',
                    'name' => 'checked',
                    'checkboxOptions' => function($model) {
                        return ['value' => $model->id];
                    },
					'contentOptions' => ['style' => 'text-align:center;'],
					'headerOptions' => ['style' => 'text-align:center;'],
                ],
                [
                    'attribute' => 'name',
                    'value' => function ($model) {
                        return Html::a(Html::encode($model->name), Url::to(["update?id={$model->id}"]));
                    },
                    'format' => 'raw',
                ],
                    [
                    'attribute' => 'status',
                    'content' => function($data) {
                        return $data->statusName;
                    },
                ],
                    [
                    'attribute' => 'project_id',
                    'content' => function($data) {
                        return $data->projectName;
                    },
					'filter' => Select2::widget([
                        'model' => $searchModel,
                        'attribute' => 'project_id',
                        'data' => ArrayHelper::Map($projects, 'id', 'name'),
                        'theme' => Select2::THEME_BOOTSTRAP,
                        'pluginOptions' => [
                            'allowClear' => true,
                        ],
                        'options' => [
                            'placeholder' => ''
                        ]
                    ]),
                ],
				'project_TZBinet',
                    [
                    'attribute' => 'date_add',
                    'content' => function($data) {
                        return date('d.m.Y H:i', strtotime($data->date_add));
                    }
                ],
                    [
                    'attribute' => 'deadline',
                    'content' => function($data) {
                        return date('d.m.Y', strtotime($data->deadline));
                    },
					'contentOptions' => function($data) {	
						if ($data->deadline < date('Y-m-d'))
                            return ['style' => 'color:red;'];
                        else
                            return [];						
                    },
                ],
                    [
                    'attribute' => 'group_id',
                    'content' => function($data) {
                        return isset($data->group_id) ? $data->group_id : '';
                    },
					'contentOptions' => ['style' => 'width: 50px;'],
                ],
                    ['class' => 'yii\grid\ActionColumn'],
            ],
        ]);
        ?>

        <?php Pjax::end(); ?>

    </div>

</div>

<script type="text/javascript">

    function deleteSelectedTasks() {

        var keys = $('#grid').yiiGridView('getSelectedRows');

        if (keys == '') {
            swal({
                title: "",
                text: 'Отметьте флажками необходимые ТЗ',
                confirmButtonColor: "#337ab7"
            });
            return;
        }

        var dialog = confirm('Удалить выбранные ТЗ?');

        if (dialog == true) {

            $.ajax({
                type: "POST",
                url: 'delete-selected-tasks',
                data: {keylist: keys},
                success: function (result) {
                    swal({
                        title: "",
                        text: result,
                        confirmButtonColor: "#337ab7"
                    });
                    $.pjax.reload({container: '#pjax_grid'});
                }
            });
        }
    }

</script>

modules/admin/views/task/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Task */

$this->title = 'Изменение: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Все ТЗ', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Изменение';
?>
<div class="task-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
    ])
    ?>

</div>